[frontend]
build = "npm run build"
show_output = true
motd = "Memory: {{teal}}{{memory_used}} MB{{end}} / {{memory_total}} MB\nCPU: {{teal}}{{cpu_percent}}%{{end}}\nUsers: {{teal}}{{active_users}}{{end}}\nHave a great day!"

[login]
disable_statuses = []
widgets = ["header", "version", "motd", "status", "sysinfo"]

[status]
show_output = true
disable_statuses = ["npm_doct", "version", "ncu", "npm_audit"]

[security]
# Specify auth cookie expire time in seconds
auth_cookie_expire_time = 3600.0
